import { useTranslation } from 'react-i18next';

const pt = {
  cta: 'Pedir análise', assess: 'Avaliar o meu consumo', quote: 'Sob orçamento', illustrative: 'Imagem ilustrativa',
  catalogNote: 'Configurações de referência. Equipamento, preço, disponibilidade e instalação são confirmados na proposta após levantamento técnico.',
  panels: 'painéis', battery: 'Bateria', inverter: 'Inversor', household: 'Para a minha casa', business: 'Para o meu negócio',
  supportTitle: 'Uma solução começa por conhecer o seu consumo.',
  supportBody: 'Kevin é o contacto da Cabo Energia. Envie o seu pedido com a ilha e o consumo aproximado. A equipa confirma a viabilidade, a cobertura e as condições antes de marcar a visita.',
  phone: 'Ligar +238 995 41 81', whatsapp: 'Falar por WhatsApp', faqTitle: 'Antes de escolher, esclareça o essencial.',
  faqs: [
    ['Funciona durante um apagão?', 'Depende da bateria, do inversor, do circuito de emergência e das cargas ligadas. O levantamento identifica os equipamentos essenciais e dimensiona a autonomia; não pressupõe que toda a casa fique alimentada sem limite.'],
    ['Quanto custa e o que está incluído?', 'O preço é confirmado numa proposta personalizada. Equipamento, instalação, impostos, transporte, trabalhos adicionais e condições de pagamento devem ficar discriminados antes da adjudicação.'],
    ['Posso instalar numa casa arrendada?', 'É necessário confirmar acesso ao telhado ou terraço, autorização do proprietário ou condomínio e condições técnicas. Pode pedir uma análise inicial mesmo sem essa confirmação.'],
    ['Como funcionam a visita e o acompanhamento?', 'O contacto inicial não obriga à compra. A equipa confirma previamente o custo e as condições da visita. Garantias por componente, manutenção e prazos de assistência ficam definidos na proposta e no contrato.'],
    ['Atendem a minha ilha?', 'Indique a ilha no pedido. A equipa confirma a disponibilidade, deslocações e calendário antes de assumir a instalação.'],
  ],
  simTitle: 'Veja um cenário para o seu consumo', simIntro: 'Uma primeira avaliação, com hipóteses visíveis. Não é um orçamento nem uma garantia de poupança.',
  bill: 'Factura mensal (CVE)', tariff: 'Tarifa de cálculo (CVE/kWh)', selfUse: 'Energia solar utilizada no local (%)', roof: 'Tenho acesso ao telhado ou terraço',
  assumptions: 'Hipóteses editáveis: tarifa de referência histórica de 32,2 CVE/kWh (não é a tarifa actual verificada), produção do catálogo com variação de ±20%, autoconsumo indicado e limite de 80% da factura para não eliminar encargos fixos. Sem receita de venda à rede. Custos de manutenção e substituição não incluídos. Confirme a tarifa na sua factura.',
  result: 'Cenário indicativo de poupança mensal', year: 'por ano', noRoof: 'Sem acesso confirmado ao telhado, esta é apenas uma hipótese. A viabilidade tem de ser avaliada antes de recomendar um sistema.',
  returnNote: 'Investimento e retorno: definidos após levantamento e confirmação do preço. A autonomia depende das cargas essenciais e da bateria.',
  next: 'Pedir avaliação deste cenário', back: 'Voltar', privacy: 'Usamos estes dados para responder ao pedido. Consulte a política de privacidade.',
  name: 'Nome', phoneLabel: 'Telemóvel', island: 'Ilha', chooseIsland: 'Escolha a ilha', error: 'Preencha nome, telefone válido e ilha.',
  saved: 'Pedido registado.', savedBody: 'A equipa recebe o seu consumo e as hipóteses da avaliação. Para falar directamente com Kevin, use o contacto abaixo.',
  sending: 'A registar…', failed: 'Não foi possível registar. Os seus dados continuam preenchidos; tente novamente ou fale por WhatsApp.',
  menu: 'Menu', close: 'Fechar',
};
type Copy = typeof pt;
const en: Copy = {
  cta:'Request assessment', assess:'Assess my consumption', quote:'Custom quote', illustrative:'Illustrative image', catalogNote:'Reference configurations. Equipment, price, availability and installation are confirmed in the proposal after a technical survey.',
  panels:'panels', battery:'Battery', inverter:'Inverter', household:'For my home', business:'For my business',
  supportTitle:'A solution starts with understanding your consumption.', supportBody:'Kevin is your contact at Cabo Energia. Include your island and approximate consumption. The team confirms feasibility, service coverage and terms before arranging a visit.', phone:'Call +238 995 41 81', whatsapp:'Talk on WhatsApp', faqTitle:'What to know before choosing.',
  faqs:[['Does it work during a power cut?','It depends on the battery, inverter, backup circuit and connected loads. The survey identifies essential equipment and sizes autonomy; it does not assume unlimited power for the entire property.'],['What does it cost and include?','Your personalised proposal confirms equipment, installation, taxes, transport, additional works and payment terms before you commit.'],['Can I install in a rented home?','Roof access, permission from the owner or condominium and technical conditions must be checked. You can request an initial assessment before these are confirmed.'],['How do the visit and support work?','Initial contact does not commit you to a purchase. Visit costs are confirmed beforehand. Component warranties, maintenance and support terms are specified in the proposal and contract.'],['Do you serve my island?','Include your island in the request. The team confirms availability, travel and timing before committing to an installation.']],
  simTitle:'Explore a scenario for your consumption',simIntro:'An initial assessment with visible assumptions. Not a quotation or a savings guarantee.',bill:'Monthly bill (CVE)',tariff:'Calculation tariff (CVE/kWh)',selfUse:'Solar energy used on site (%)',roof:'I have roof or terrace access',assumptions:'Editable assumptions: historical reference tariff 32.2 CVE/kWh (not a verified current tariff), catalogue production with ±20% variation, selected self-consumption and an 80% bill cap to retain fixed charges. No export revenue. Maintenance and replacement costs excluded. Check your tariff on your bill.',result:'Indicative monthly savings scenario',year:'per year',noRoof:'Without confirmed roof access, this is only a scenario. Feasibility must be checked before recommending a system.',returnNote:'Investment and payback are determined after a survey and price confirmation. Backup duration depends on essential loads and battery capacity.',next:'Request an assessment',back:'Back',privacy:'We use these details to respond to your request. Read our privacy policy.',name:'Name',phoneLabel:'Phone',island:'Island',chooseIsland:'Choose your island',error:'Enter a name, valid phone number and island.',saved:'Request saved.',savedBody:'The team receives your consumption and assessment assumptions. To talk directly with Kevin, use the contact below.',sending:'Saving…',failed:'We could not save your request. Your details are preserved; retry or contact us on WhatsApp.',menu:'Menu',close:'Close',
};
const fr: Copy = {
  cta:'Demander une analyse', assess:'Évaluer ma consommation',quote:'Sur devis',illustrative:'Image illustrative',catalogNote:'Configurations de référence. Équipement, prix, disponibilité et installation sont confirmés dans le devis après une visite technique.',panels:'panneaux',battery:'Batterie',inverter:'Onduleur',household:'Pour mon logement',business:'Pour mon entreprise',supportTitle:'Une solution commence par comprendre votre consommation.',supportBody:'Kevin est votre contact chez Cabo Energia. Indiquez votre île et votre consommation approximative. L’équipe confirme la faisabilité, la couverture et les conditions avant de prévoir une visite.',phone:'Appeler +238 995 41 81',whatsapp:'Parler sur WhatsApp',faqTitle:'Les points essentiels avant de choisir.',
  faqs:[['Le système fonctionne-t-il pendant une coupure ?','Cela dépend de la batterie, de l’onduleur, du circuit de secours et des charges raccordées. La visite identifie les équipements essentiels et dimensionne l’autonomie ; elle ne suppose pas une alimentation illimitée du bâtiment.'],['Quel est le prix et que comprend-il ?','Le devis personnalisé précise les équipements, l’installation, les taxes, le transport, les travaux supplémentaires et les modalités de paiement avant votre engagement.'],['Puis-je installer dans un logement loué ?','Il faut vérifier l’accès au toit, l’accord du propriétaire ou de la copropriété et les conditions techniques. Une première analyse peut être demandée avant ces confirmations.'],['Comment se déroulent la visite et le suivi ?','Le premier contact n’engage pas à acheter. Le coût de la visite est confirmé au préalable. Garanties, entretien et assistance sont précisés dans le devis et le contrat.'],['Intervenez-vous sur mon île ?','Indiquez votre île. L’équipe confirme la disponibilité, les déplacements et le calendrier avant tout engagement.']],
  simTitle:'Explorez un scénario pour votre consommation',simIntro:'Une première évaluation avec des hypothèses visibles. Ni devis ni garantie d’économie.',bill:'Facture mensuelle (CVE)',tariff:'Tarif de calcul (CVE/kWh)',selfUse:'Énergie solaire utilisée sur place (%)',roof:'J’ai accès au toit ou à une terrasse',assumptions:'Hypothèses modifiables : tarif historique de référence de 32,2 CVE/kWh (pas un tarif actuel vérifié), production du catalogue ±20 %, autoconsommation choisie et plafond de 80 % de la facture pour conserver les frais fixes. Sans revenus de revente. Entretien et remplacement exclus. Vérifiez votre tarif sur votre facture.',result:'Scénario indicatif d’économie mensuelle',year:'par an',noRoof:'Sans accès confirmé au toit, il ne s’agit que d’une hypothèse. La faisabilité doit être vérifiée avant de recommander un système.',returnNote:'Investissement et amortissement sont déterminés après visite et confirmation du prix. L’autonomie dépend des charges essentielles et de la batterie.',next:'Demander une évaluation',back:'Retour',privacy:'Ces données servent à répondre à votre demande. Consultez notre politique de confidentialité.',name:'Nom',phoneLabel:'Téléphone',island:'Île',chooseIsland:'Choisissez votre île',error:'Indiquez un nom, un téléphone valide et une île.',saved:'Demande enregistrée.',savedBody:'L’équipe reçoit votre consommation et les hypothèses de l’évaluation. Pour parler directement à Kevin, utilisez le contact ci-dessous.',sending:'Enregistrement…',failed:'Enregistrement impossible. Vos informations sont conservées ; réessayez ou contactez-nous sur WhatsApp.',menu:'Menu',close:'Fermer',
};
export function useCommercialCopy() { const { i18n } = useTranslation(); return i18n.language.startsWith('fr') ? fr : i18n.language.startsWith('en') ? en : pt; }
